### ISSUE TITLE
Auto add required modules

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/puppet_litmus#167]
## Use Case
If a module's fixtures file does not contain the required fixtures for litmus to work, it can be a burden on the user to add them each time.  (100s of modules).

Without this a user would see errors like:

```
puppet_agent was not found in websphere/spec/fixtures/modules, please amend the .fixtures.yml file
```
## Describe the Solution You Would Like
Add a new task named setup_module that does some basic conversion.  As part of this conversion dynamically add the required fixtures to the fixtures file if they don't already exist.

```yaml
    provision: 'https://github.com/puppetlabs/provision'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    translate: 'git://github.com/puppetlabs/puppetlabs-translate.git'
```

This new task or maybe just a helper method should be called before the install_agent task.

## Describe Alternatives You've Considered
N/A

## Additional Context
I have some code that does this and can make a PR.  One gotcha is that some organizations will require custom urls so we can't statically define all the required modules and should make the list editable.  Maybe a litmus_modules.yaml file in the root of the module.
