### ISSUE TITLE
A "platform" fact should not be required in inventory.yaml

### ISSUE THREAD

**Issue by luksi1** [puppetlabs/puppet_litmus#269]
## Describe the Bug
Virtually all Litmus commands require an inventory.yaml file to provide a "platform" fact.

## Expected Behavior
This does not really follow the docs in my opinion. We should be able to simply provide a target and then run a plan, task, serverspec test... whatever, without needing to produce a "platform" fact as is the case with run_shell, bolt_upload_file, run_bolt_task, bolt_run_script...

## Steps to Reproduce
1. Create an inventory.yaml file as such:
```
version: 2
groups:
- name: ssh_nodes
  targets:
  - config:
      transport: ssh
      ssh:
        user: sut
        host-key-check: false
        run-as: root
    uri: foo.domain.com
```
2. Run a spec test such as:
```
describe 'file creation' do
  context 'mkdir /tmp/foo' do
    it 'creates /tmp/foo' do
      expect(run_shell('mkdir /tmp/foo').stderr).to eq('')
    end
  end
end
```

This will produce something like this:

```
     NoMethodError:
       undefined method `[]' for nil:NilClass

     # /home/gitlab-runner/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.17.0/lib/puppet_litmus/puppet_helpers.rb:164:in `block in run_shell'
     # /home/gitlab-runner/.pdk/cache/ruby/2.5.0/gems/honeycomb-beeline-2.0.0/lib/honeycomb/client.rb:65:in `start_span'
     # /home/gitlab-runner/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.17.0/lib/puppet_litmus/puppet_helpers.rb:153:in `run_shell'
     # ./spec/acceptance/elasticsearch_pp_spec.rb:51:in `block (3 levels) in <top (required)>'
```
This is due to the fact that in run_shell, you have this line:

```
span.add_field('litmus.platform', facts_from_node(inventory_hash, target_node_name)['platform'])
```
This means that we would need to add "platform" as a fact in the inventory.yaml file.

Something like this gets past the error:

```
version: 2
groups:
- name: ssh_nodes
  targets:
  - config:
      transport: ssh
      ssh:
        user: sut
        host-key-check: false
        run-as: root
    uri: foo.domain.com
    fact:
      platform: unix
```

## Environment
 - Version: 0.17.0
 - Platform: Ubuntu 18.04
