### ISSUE TITLE
Error "Failed provisioning ubuntu:18.04 using docker" in Gitlab-CI context

### ISSUE THREAD

**Issue by mfaure** [puppetlabs/puppet_litmus#292]
## Describe the Bug

(I don't know if this is a bug, but at least I share a reproducible use case)

I can't provision with Litmus with Gitlab-CI, I've got the error `Failed provisioning ubuntu:18.04 using docker`

* Here is the full [log of the CI job](https://gitlab.com/taqamaqa-puppet/app_vhost_debug/-/jobs/539324325)
* Here is the [`.gitlab-ci.yml` file](https://gitlab.com/taqamaqa-puppet/app_vhost_debug/-/blob/master/.gitlab-ci.yml)

## Expected Behavior

Have provisioning with Litmus in Gitlab-CI working

## Steps to Reproduce

1. Create a project on any gitlab
1. Grab the code from https://gitlab.com/taqamaqa-puppet/app_vhost_debug/
1. Push the code to the project on gitlab and watch *Project* > CI/CD > Jobs

(one may re-run a failed job, with suitable privileges)

## Environment

* Bundler version 1.17.3
* Gem version 3.0.3
* Project is created with PDK 1.17
* Gitlab Runner is a shared one from Gitlab.com
* Gitlab Runner Executor is "docker+machine"
* Base image (of runner) is Ruby:2.5.7

## Additional Context

* I also tried with a dedicated runner (on my laptop) with executor "docker": result is the same.

**Comment by mfaure** [comment]
Harvesting Github, I found one example of `.gitlab-ci.yml` file using Litmus: [
puppet-passless/.gitlab-ci.yml ](https://github.com/wavesoftware/puppet-passless/blob/9ebf881612f66838aed1a0d473dfdec4d51a679b/.gitlab-ci.yml).

**Comment by david22swan** [comment]
@mfaure Hey, just took a quick look at your error file and the problem seems to have risen from the lack of an inventory.yaml file. 
There are two options to resolve this, firstly you could convert to using an provision.yaml and the provision_list command as this command generates the inventory.yaml.
The other option would be to add the following command to your file in order to create it manually:
```
cat <<EOF >> inventory.yaml
        ---
        version: 2
        groups:
        - name: docker_nodes
          targets: []
        - name: ssh_nodes
          targets: []
        - name: winrm_nodes
          targets: []
        EOF
```
I hope this is useful for you.

**Comment by mfaure** [comment]
Thank you @david22swan I added the `inventory.yaml` but [result is the same](https://gitlab.com/taqamaqa-puppet/app_vhost_debug/-/jobs/540868655). This is somehow consistent as `inventory.yaml` was included in `.gitignore` by PDK.

Another track I have to test (thanks to a private message from @Dan33l) is to use, for the Gitlab Runner, either a "shell executor" or an executor compatible with Docker-in-Docker (with Kaniko docker image). I found the Gitlab doc [Building Docker images with GitLab CI/CD](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html).

**Comment by DavidS** [comment]
The pertinent error in the log you link is [here](https://gitlab.com/taqamaqa-puppet/app_vhost_debug/-/jobs/539324325#L228):
```
Failed provisioning ubuntu:18.04 using docker
{"target"=>"localhost", "action"=>"task", "object"=>"provision::docker", "status"=>"failure", "value"=>{"_error"=>{"kind"=>"provision/docker_failure", "msg"=>"No such file or directory - docker", "backtrace"=>["/usr/local/lib/ruby/2.5.0/open3.rb:199:in `spawn'", "/usr/local/lib/ruby/2.5.0/open3.rb:199:in `popen_run'", "/usr/local/lib/ruby/2.5.0/open3.rb:95:in `popen3'", "/usr/local/lib/ruby/2.5.0/open3.rb:258:in `capture3'", "/tmp/b1e9acd1-1625-49b6-9f60-95f24b9fc2b9/provision/tasks/docker.rb:88:in `block in provision'", "/tmp/b1e9acd1-1625-49b6-9f60-95f24b9fc2b9/provision/tasks/docker.rb:83:in `each'", "/tmp/b1e9acd1-1625-49b6-9f60-95f24b9fc2b9/provision/tasks/docker.rb:83:in `provision'", "/tmp/b1e9acd1-1625-49b6-9f60-95f24b9fc2b9/provision/tasks/docker.rb:150:in `<main>'"]}}}
```
specifically "No such file or directory - docker".

I'm not very familiar with gitlab CI, but from your last message, I'm assuming the job is running in a docker container, and from the error message it doesn't seem to have docker installed in it.

If you want to use the docker provisioner, by definition, you need to have a viable docker installation available to litmus.

**Comment by carabasdaniel** [comment]
Hi @mfaure,

I'm going to close this issue as it related to the machine configuration on which the provisioning is running -> basically missing docker installation in PATH as dependency from what I understand based on @DavidS's comment. 

Please feel free to re-open if necessary.

**Comment by maxadamo** [comment]
I'm not sure about the cause of this issue and I definitely have the same issue explained in this bug. 
Docker is certainly available, as you can see from Line 4 of the log file [here](https://gitlab.com/taqamaqa-puppet/app_vhost_debug/-/jobs/539324325#L4)
But I am not understanding is this one:
```yaml
  stage: acceptance
  image: ruby:2.5.7
  script:
    - bundle exec rake 'litmus:provision[docker, ubuntu:18.04]'
    - bundle exec rake litmus:install_agent
    - bundle exec rake litmus:install_module
    - bundle exec rake litmus:acceptance:parallel
  after_script:
    - bundle exec rake litmus:tear_down
  variables:
    PUPPET_GEM_VERSION: "~> 6"
```
it means: 
- use the docker image `ruby:2.5.7`
- then run `bundle exec rake 'litmus:provision[docker, ubuntu:18.04]'` to provision another docker image

and it doesn't make any sense :confused: 

p.s.: If I have console access to Gitlab server, I install PDK and I let the CI run `bundle exec rake 'litmus:provision[docker, ubuntu:18.04]'` using a shell runner, instead of a docker runner. This is not possible if we use the cloud.
