### ISSUE TITLE
sudo password asked when executing litmus tests

### ISSUE THREAD

**Issue by johnqa** [puppetlabs/puppet_litmus#293]
[edit: fixed formatting of code snippets]

Hi,

I am trying to implement acceptance testing with Litmus for our Puppet code base but due to internal environment restrictions I cannot use Litmus to provision hosts and I use our own provisioning system. Then I write my own inventory.yaml with something like:

```
 - name: ssh_nodes
   targets:
   - uri: machine_name
     config:
       transport: ssh
       ssh:
         user: non_root_user
         password: user_password
         port: 22
```

The problem is that the user is not root but has sudo rights.

When running `pdk bundle exec rake litmus:acceptance:machine_name` I get this error:
```
pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.13.0
[DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/workspace/PDK/private/puppet/ruby/2.5.0/gems/win32-service-0.8.8/lib/win32/windows/structs.rb:67:in <class:SERVICE_STATUS_PROCESS> will be disallowed in ffi-2.0.
C:/workspace/PDK/private/ruby/2.5.7/bin/ruby.exe -I'C:/Users/xxx/AppData/Local/PDK/cache/ruby/2.5.0/gems/rspec-core-3.9.2/lib';'C:/Users/xxx/AppData/Local/PDK/cache/ruby/2.5.0/gems/rspec-support-3.9.3/lib' 'C:/Users/xxx/AppData/Local/PDK/cache/ruby/2.5.0/gems/rspec-core-3.9.2/exe/rspec' --pattern 'spec/acceptance/**{,/*/**}/*_spec.rb'
Wrong sudo password! Please confirm your password on machine_name.
No examples found.
```

I have searched all over internet with no use. Do you have any idea on how to work around this?

Thank you,
John
