### ISSUE TITLE
Unreleased modules needs a manual upload to docker

### ISSUE THREAD

**Issue by JGodin-C2C** [puppetlabs/puppet_litmus#503]
## Describe the Bug
When creating a new module or a private module, if the module is not on the forge, one needs to upload it to the docker where the tests are performed

## Expected Behavior
When creating a new module or a private module, litmus should build the local module and upload it to the docker where the test are performed

## Steps to Reproduce
1. Create a new module `pdk new module mymodule`
2. add some dependencies
In metadata.json:
```
    {
      "name": "puppetlabs/stdlib",
      "version_requirement": "=9.0.0"
    },
    {
      "name": "puppetlabs/apache",
      "version_requirement": "=10.1.0"
    }
```
in .fixtures.yml
```
---
fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    portage: "https://github.com/gentoo/puppet-portage.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: '>= 6.0.0'

```
settup the provision.yaml
```
---
default:
  provisioner: docker_exp
  images:
  - litmusimage/centos:stream8
```
4. Launch the litmus  provisioner `pdk bundle exec rake 'litmus:provision[docker_exp, litmusimage/centos:stream8]'`
5. Install the puppet agent `pdk bundle exec rake 'litmus:install_agent'`
6. Try to install the module : `pdk bundle exec rake 'litmus:install_module'`
